// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
using azure_proto_core;

namespace Inheritance.Models
{
    // This overrides the autogenerated base class
    internal partial class ClassThatInheritsFromBaseClassAndSomePropertiesWithBaseClassOverride: TrackedResource
    {
    }
}