trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure

jobs:
  - job: Build
    variables:
      DotNetCoreSDKVersion: 3.0.100
    pool:
      vmImage: windows-2019
    steps:
      - checkout: self
      - task: DotNetCoreInstaller@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          version: "$(DotNetCoreSDKVersion)"
      - task: NodeTool@0
        displayName: "Install Node 13.x"
        inputs:
          versionSpec: '13.x'
      - script: |
          npm ci
        displayName: "Install packages"
        workingDirectory: autorest.csharp
      - script: |
          dotnet build AutoRest.CSharp.V3.sln
        displayName: "Build"
        workingDirectory: autorest.csharp
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - checkout: azure-sdk-tools
        path: azure-sdk-tools
      - checkout: azure-sdk-for-net
        path: azure-sdk-for-net
      - pwsh: ./autorest.csharp/eng/UpdateAzureSdkForNet.ps1 -Version $(AutorestCSharpVersion) -SdkRepoRoot $(System.DefaultWorkingDirectory)/azure-sdk-for-net
        condition: succeeded()
        failOnStderr: false
        displayName: 'Update generator version in Azure SDK repo'
      - template: /eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
        parameters:
          RepoName: azure-sdk-for-net
          PRBranchName: auto-update-autorest
          CommitMsg: Update AutoRest C# version
          PRTitle: Update AutoRest C# version to $(AutorestCSharpVersion)
          PushArgs: -f
          WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-for-net
          ScriptDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools/eng/common/scripts
  - template: smoke-test.yml
    parameters:
      name: SmokeTest_A_C
      filter: "^[a-b]"
  - template: smoke-test.yml
    parameters:
      name: SmokeTest_C_I
      filter: "^[c-i]"
  - template: smoke-test.yml
    parameters:
      name: SmokeTest_J_R
      filter: "^[j-r]"
  - template: smoke-test.yml
    parameters:
      name: SmokeTest_S_Z
      filter: "^[s-z]"
