trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

jobs:
  - job: Build
    variables:
      DotNetCoreSDKVersion: 3.0.100
      ProjectDirectory: src/AutoRest.CSharp.V3/
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          version: "$(DotNetCoreSDKVersion)"
      - script: |
          npm install
        displayName: "Install packages"
      - script: |
          dotnet build AutoRest.CSharp.V3.sln
        displayName: "Build"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
#      - pwsh: ./eng/CodeChecks.ps1
#        displayName: "Check if code is up-to-date"
      - script: |
          dotnet test AutoRest.CSharp.V3.sln
        displayName: "Test"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - script: |
          dotnet pack /t:NpmPackage $(ProjectDirectory) -o $(Build.ArtifactStagingDirectory)
        displayName: "Publish NPM package"
      - task: PublishPipelineArtifact@1
        condition: succeeded()
        inputs:
          artifactName: packages
          path: $(Build.ArtifactStagingDirectory)
      - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
        - script: |
            export DEV_VERSION=$(node -p -e "require('./$(ProjectDirectory)package.json').version")-dev.$BUILD_BUILDNUMBER
            npm version --no-git-tag-version $DEV_VERSION
            npm pack
            npx publish-release --token $(Github-azuresdkci-personalaccesstoken) --repo autorest.csharp --owner azure --name v$DEV_VERSION --tag v$DEV_VERSION --notes='prerelease build' --prerelease --editRelease false --assets autorest-csharp-$DEV_VERSION.tgz --target_commitish $(Build.SourceBranchName)
          displayName: 'Publish to GitHub'
